ignoreFiles:
  - \.DS_Store$
  - \.vscode$
  - .*\.code-workspace$
  - frontmatter\.json$

outputFormats:
  printFormat:
    name: print
    notAlternative: false
    mediaType: text/html
    baseName: print
    isPlainText: false
    rel: alternate
    isHTML: true
    noUgly: true
    permalinkable: false

# NOTICE: Make sure that output format "print" is only generated in devel and test environment
outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML

# NOTICE: To produce printable PDFs, add the settings below to the
# config for the devel environment
# outputs:
#   home:
#     - HTML
#     - print
#   page:
#     - HTML
#     - print
#   section:
#     - HTML
#     - print

Author:
  name: Simon Heimlicher

Security:
  _merge: deep
  enableInlineShortcodes: false
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^babel$
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^HUGO_
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*

Imaging:
  anchor: Smart
  resampleFilter: Lanczos
  hint: photo
  quality: 85
