vitae:

# ------ Template EXECUTIVE --------- #
  executive:
    contact:
      # title: section-contact
      title: false
      screen: true
      print: true
    links:
      screen: true
      print: true
    parts:
      # Front page
      - template: front-page
        pagination_policy: first
        slots:
        - slot: header
          sections:
          - section: header
            components:
            - component: header
              portrait: true
              degrees: true
              tagline: true
              fragments:
              - fragment: contact
              - fragment: date-of-birth
        - slot: main
          sections:
          - section: personal-profile
            title: section-personal-profile
            components:
            - component: profile
          - section: career-summary
            title: section-career-summary
            components:
            - component: stages
              collection: stages
              filter_by: type
              filter_value: professional
              headings: true
              organization_period: true
              role_period: true
              logo: false
              skills: false
              details: false
              results: false
              responsibilities: false
              achievements: false
          - section: language-skills
            title: section-language-skills
            components:
            - component: skills
              collection: skills
              filter_by: type
              filter_value: language
              details: false
              level_bar: false
          - section: award-selection
            title: section-awards
            components:
            - component: awards
              details: false
              screen: true
              print: true

        - slot: footer
          sections:
          - section: connect
            title: section-connect
            components:
            - component: links
              screen: true
              print: true
      # Career timeline
      - template: career-timeline
        pagination_policy: break
        slots:
        - slot: main
          sections:
          - section: experience
            title: section-experience
            components:
            - component: stages
              collection: stages
              filter_by: type
              filter_value: professional
              organization_period: true
              role_period: true
              organization_duration: true
              role_duration: true
              skills: false
              responsibilities: true
              details: false
              headings: true
          - section: education
            title: section-education
            components:
            - component: stages
              collection: stages
              filter_by: type
              filter_value: education
      # Appendix
      # - template: main-aside-primary
      #   pagination_policy: break
      #   slots:
      #   - slot: main
      #     sections:
      #       - section: patent-selection
      #         components:
      #         - component: publications
      #           collection: publications
      #           filter_by: kind
      #           filter_value: patent
      #           title: section-patents
      #           screen: true
      #           print: true
      #         - component: publications
      #           collection: publications
      #           filter_by: kind
      #           filter_value: publication
      #           title: section-publications
      #           remark: selected-publications
      #           screen: true
      #           print: true

# ------ Template RESUME --------- #
  resume:
    contact:
      title: section-contact
      screen: true
      print: true
    links:
      screen: true
      print: true
    header:
      - main:
          - feature: about
            title: false
            level: 1
            portrait: true
            tagline: true
            profile: true
            contact: true
    pages:
      - main:
          - feature: stages
            collection: stages
            filter_by: type
            filter_value: professional
            title: section-experience
            organization_period: true
            role_period: true
            organization_duration: true
            role_duration: true
            timeline_for_single_role: true
            responsibilities: true
            results: true
            headings: true
            skills: false
        primary:
          - feature: stages
            collection: stages
            filter_by: type
            filter_value: education
            title: section-education
          - feature: skills
            collection: skills
            filter_by: type
            filter_value: language
            title: section-language-skills
          - feature: awards
            title: section-awards
            screen: true
            print: true
          - feature: publications
            collection: publications
            filter_by: kind
            filter_value: patent
            title: section-patents
            screen: true
            print: true
          # - feature: publications
          #   collection: publications
          #   filter_by: kind
          #   filter_value: publication
          #   title: section-publications
          #   remark: selected-publications
          #   screen: true
          #   print: true
          - feature: links
            title: section-connect
            screen: true
            print: true

# ------ Template LETTER --------- #
  letter:
    about:
      portrait: false
      tagline: true
      contact: true
    contact:
      title: false
      screen: true
      print: true
    links:
      title: false
      screen: true
      print: true
    header:
      - main:
          - feature: about
            title: false
            contact: true
    pages:
      - main:
          - feature: application
            subject: application-for-position
            level: 1
            address: true
            screen: true
            print: true
        primary:
          - feature: links
            title: false
            screen: true
            print: true

# ------ Template PROFILE --------- #
  profile:
    header:
      - main:
          - feature: about
            title: false
            portrait: true
            tagline: true
            profile: true
            contact: true
          - feature: links
            title: false
            screen: true
            print: true
