vitae:

# ------ Template EXECUTIVE --------- #
  executive:
    contact:
      # title: section-contact
      title: false
      screen: true
      print: true
    links:
      screen: true
      print: true

    parts:

      # Front page
      - template: front-page
        # enabled: false
        pagination_policy: first
        slots:
        - slot: header
          sections:
          - section: header
            components:
            - component: header
              portrait: true
              degrees: true
              tagline: true
              # style:
              #   font-size: larger-1
              fragments:
              - fragment: contact
              - fragment: personal
                fields:
                - field: date_of_birth
                - field: citizenship
                  title: fragment_citizenship
        - slot: main
          sections:
          - section: personal-profile
            title: section-personal-profile
            container: section
            components:
            - component: panels
              collection: profile
              # style:
              #   font-size: larger-1
          - section: career-summary
            title: section-career-summary
            container: section
            components:
            - component: stages
              collection: stages
              filter_by: type
              filter_value: professional
              links: false
              date_format: 2006
              unit: 1
              style:
                # timeline: shallow
                # timeline: column
                # timeline: dot-dash
                layout: compact
                # heading: larger-1
                heading: normal
                # logo: false
                # logo: left
              function: false
              label:
                function: false
                unit: false
              organization:
                period: true
                details: false
              role:
                period: true
                details: false
                summary: false
                description: false
                responsibilities_achievements: false
                star: false
                skills: false
                results: false
                responsibilities: false
                achievements: false
          # - section: award-selection
          #   title: section-awards
          #   container: section
          #   components:
          #   - component: awards
          #     details: false
          #     screen: true
          #     print: true
          #     style:
          #       logo: false
          # - section: language-skills
          #   title: section-language-skills
          #   container: section
          #   components:
          #   - component: skills
          #     collection: skills
          #     filter_by: type
          #     filter_value: language
          #     details: false
          #     level_bar: true
          # - section: connect
          #   title: section-connect
          #   container: section
          #   components:
          #   - component: links
          #     screen: true
          #     print: true

          - section: key-achievements
            title: section-key-achievements
            container: section
            components:
            - component: panels
              collection: achievements
              # style:
              #   font-size: larger-1
        # - slot: footer
        #   sections:
        #   - section: connect
        #     title: section-connect
        #     components:
        #     - component: links
        #       screen: true
        #       print: true

      # Career timeline
      - template: career-timeline
        # enabled: false
        pagination_policy: break
        slots:
        - slot: main
          sections:
          - section: experience
            title: section-experience
            components:
            - component: stages
              collection: stages
              filter_by: type
              filter_value: professional
              style:
                timeline: column
                logo: left
                # timeline: dot-dash
              organization:
                period: true
                # duration: true
                details: true
              role:
                headings: false
                period: true
                duration: false
                details: true
                summary: false
                description: false
                responsibilities_achievements: true
                star: false
                skills: false
                responsibilities: false
                achievements: false

      # Appendix
      - template: appendix
        pagination_policy: first
        slots:
        - slot: main
          sections:
          - section: education
            # enabled: false
            title: section-education
            container: section
            components:
            - component: stages
              collection: stages
              filter_by: type
              filter_value: education
              style:
                timeline: column
                logo: left
              # organization:
              #   period: true
              #   duration: true
              #   details: true
              role:
                period: true
                duration: false
                details: true
                description: true
          # - section: language-skills
          #   title: section-language-skills
          #   components:
          #   - component: skills
          #     collection: skills
          #     filter_by: type
          #     filter_value: language
          #     details: false
          #     level_bar: true
          - section: patent-selection
            title: section-patents
            container: section
            components:
            - component: publications
              collection: publications
              filter_by: kind
              filter_value: patent
              screen: true
              print: true
          - section: publication-selection
            title: section-publications
            container: section
            components:
            - component: publications
              collection: publications
              filter_by: kind
              filter_value: publication
              screen: true
              print: true
          - section: award-selection
            title: section-awards
            container: section
            components:
            - component: awards
              details: false
              screen: true
              print: true
              style:
                logo: false
          - section: language-skills
            title: section-language-skills
            container: section
            components:
            - component: skills
              collection: skills
              filter_by: type
              filter_value: language
              details: false
              level_bar: true
        # - slot: footer
        #   sections:
        #   - section: connect
        #     title: section-connect
        #     container: section
        #     components:
        #     - component: links
        #       screen: true
        #       print: true

    # Footer to be repeated on every printed page
    footer:
      template: name-page-number
      components:
      - component: footer
        # style:
        #   font-size: normal
        fragments:
          - fragment: page-meta
            fields:
              # - field: content-type
              #   content: Resume of
              #   align: start
              - field: name
                content: "{personal.name}"
                align: start
              - field: content-type
                content: Resume
                align: center
              - field: page-number
                content: "{page-number}"
                align: end
              - field: page-of-total
                content: '|'
                align: end
              - field: total-pages
                content: "{total-pages}"
                align: end

# ------ Template RESUME --------- #
  resume:
    contact:
      title: section-contact
      screen: true
      print: true
    links:
      screen: true
      print: true
    header:
      - main:
          - feature: about
            title: false
            level: 1
            portrait: true
            tagline: true
            profile: true
            contact: true
    pages:
      - main:
          - feature: stages
            collection: stages
            filter_by: type
            filter_value: professional
            title: section-experience
            organization_period: true
            role_period: true
            organization_duration: true
            role_duration: true
            timeline_for_single_role: true
            responsibilities: true
            results: true
            headings: true
            skills: false
        primary:
          - feature: stages
            collection: stages
            filter_by: type
            filter_value: education
            title: section-education
          - feature: skills
            collection: skills
            filter_by: type
            filter_value: language
            title: section-language-skills
          - feature: awards
            title: section-awards
            screen: true
            print: true
          - feature: publications
            collection: publications
            filter_by: kind
            filter_value: patent
            title: section-patents
            screen: true
            print: true
          # - feature: publications
          #   collection: publications
          #   filter_by: kind
          #   filter_value: publication
          #   title: section-publications
          #   remark: selected-publications
          #   screen: true
          #   print: true
          - feature: links
            # title: section-connect
            title: false
            screen: true
            print: true

# ------ Template LETTER --------- #
  letter:
    about:
      portrait: false
      tagline: true
      contact: true
    contact:
      title: false
      screen: true
      print: true
    links:
      title: false
      screen: true
      print: true
    header:
      - main:
          - feature: about
            title: false
            contact: true
    pages:
      - main:
          - feature: application
            subject: application-for-position
            level: 1
            address: true
            screen: true
            print: true
        primary:
          - feature: links
            title: false
            screen: true
            print: true

# ------ Template PROFILE --------- #
  profile:
    header:
      - main:
          - feature: about
            title: false
            portrait: true
            tagline: true
            profile: true
            contact: true
          - feature: links
            title: false
            screen: true
            print: true
